version: 2.1

workflows:
  pipeline:
    jobs:
      - build-test-lint
      - containerization:
          requires:
            - build-test-lint
          filters:
            branches:
              only: setup-circleci

orbs:
  python: circleci/python@1.2

jobs:
  build-test-lint: 
 
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            pip install flake8-html
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"

      - run:
          name: Running tests
          command: |
            . env/bin/activate
            python3 manage.py test

      - run:
          name: Running linting
          command: |
            . env/bin/activate
            flake8 --exclude **/migrations/*,env \ --max-line-length 99 --format=html --htmldir=flake-report

      - store_artifacts:
          path: flake-report/
          destination: python_app

  containerization:
    docker:
      - image: cimg/python:3.8
    
    steps:
      - checkout
      - setup_remote_docker

      # build and push Docker image
      - run:
          name: Package app and push to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t maeriz/oc_lettings:$CIRCLE_SHA1 .
            docker push maeriz/oc_lettings:$CIRCLE_SHA1